
export const Router = {
    "root": "/",
    "login": "/login",
    "verificar": "/verificar",
    "register": "/register",
    "registeEmpresa": "/register-empresa",
    "dashboard": "/dashboard",
    "catalogo": "/catalogo",
    "adminInventario": "/admin-inventario",
    "adminUsuarios": "/admin-usuarios",
    "adminFacturas": "/admin-facturas",
    "adminLog": "/admin-log",
    "categorias": "/categorias",
    "detalle": "/detalle",
    "principal": "/principal",
    "carrito": "/carrito",
    "procesoCompraConfirmar": "/proceso-compra-confirmar",
    "procesoCompraDatos": "/proceso-compra-datos",
    "procesoCompraPago": "/proceso-compra-pago",
    "procesoFactura": "/proceso-factura",
    "historialCompra": "/historialCompra",
    "userCuenta": "/user-cuenta",
    "userFavoritos": "/user-favoritos",
}